# Generated by Django 4.2 on 2023-06-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_review_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfull',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='productfull',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AlterField(
            model_name='productfull',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
