# Generated by Django 4.2 on 2023-06-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productfull_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfull',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
