# Generated by Django 4.2 on 2023-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productfull_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfull',
            name='limited_edition',
            field=models.BooleanField(default=False),
        ),
    ]
