# Generated by Django 4.2 on 2023-06-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productfull_limited_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfull',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
