# Generated by Django 4.2 on 2023-06-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productfull_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfull',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
