# Generated by Django 4.2 on 2023-06-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productfull_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfull',
            name='tags',
            field=models.ManyToManyField(blank=True, to='products.tag'),
        ),
    ]
