# Generated by Django 4.2 on 2023-06-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfull',
            name='dateFrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productfull',
            name='dateTo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productfull',
            name='salePrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
