# Generated by Django 4.2 on 2023-06-07 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_productfull_datefrom_productfull_dateto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfull',
            name='specifications',
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('value', models.CharField(blank=True, max_length=50)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Specifications', to='products.productfull')),
            ],
        ),
    ]
