# Generated by Django 4.2 on 2023-06-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_productfull_specifications_specifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specifications',
            options={'verbose_name': 'Specifications', 'verbose_name_plural': 'Specifications'},
        ),
        migrations.RemoveField(
            model_name='specifications',
            name='product',
        ),
        migrations.AddField(
            model_name='specifications',
            name='product',
            field=models.ManyToManyField(to='products.productfull'),
        ),
    ]
