# Generated by Django 4.2 on 2023-06-07 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_specifications_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specifications',
            name='product',
        ),
        migrations.AddField(
            model_name='specifications',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.productfull'),
        ),
    ]
