# Generated by Django 4.2 on 2023-06-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_specifications_product_specifications_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specifications',
            name='product',
        ),
        migrations.AddField(
            model_name='productfull',
            name='specifications',
            field=models.ManyToManyField(to='products.specifications'),
        ),
    ]
