# Generated by Django 4.2 on 2023-06-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_categoryimage_remove_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ManyToManyField(null=True, to='products.categoryimage'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ManyToManyField(null=True, to='products.categoryimage'),
        ),
    ]
