# Generated by Django 4.2 on 2023-06-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_category_id_delete_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='src',
            field=models.FileField(upload_to='categoryimages/'),
        ),
    ]
