# Generated by Django 4.2.2 on 2023-06-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_categoryimage_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfull',
            name='category',
        ),
        migrations.AddField(
            model_name='productfull',
            name='category',
            field=models.ManyToManyField(blank=True, to='products.category'),
        ),
    ]
