# Generated by Django 4.2.2 on 2023-06-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_quantity_basketitem_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitem',
            old_name='product',
            new_name='products',
        ),
    ]
