# Generated by Django 4.2.2 on 2023-06-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_product_basketitem_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitem',
            old_name='products',
            new_name='product',
        ),
    ]
