# Generated by Django 4.2 on 2023-06-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express', models.DecimalField(decimal_places=2, max_digits=8)),
                ('regular', models.DecimalField(decimal_places=2, max_digits=8)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Orders History', 'verbose_name_plural': 'Orders Histories'},
        ),
    ]
